// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.verding.edo.model;

import it.verding.edo.model.Bar;

privileged aspect Bar_Roo_JavaBean {
    
    public String Bar.getBirra() {
        return this.birra;
    }
    
    public void Bar.setBirra(String birra) {
        this.birra = birra;
    }
    
}
