// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.verding.edo.model;

import it.verding.edo.model.TipoCombustibile;

privileged aspect TipoCombustibile_Roo_JavaBean {
    
    public String TipoCombustibile.getNome() {
        return this.nome;
    }
    
    public void TipoCombustibile.setNome(String nome) {
        this.nome = nome;
    }
    
}
