// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.verding.edo.domain;

import it.verding.edo.domain.TipoEnte;

privileged aspect TipoEnte_Roo_JavaBean {
    
    public String TipoEnte.getNome() {
        return this.nome;
    }
    
    public void TipoEnte.setNome(String nome) {
        this.nome = nome;
    }
    
}
