// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.verding.edo.model;

import it.verding.edo.model.BarDataOnDemand;
import it.verding.edo.model.BarIntegrationTest;
import it.verding.edo.service.BarService;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect BarIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BarIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BarIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    BarDataOnDemand BarIntegrationTest.dod;
    
    @Autowired
    BarService BarIntegrationTest.barService;
    
    @Test
    public void BarIntegrationTest.testCountAllBars() {
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", dod.getRandomBar());
        long count = barService.countAllBars();
        Assert.assertTrue("Counter for 'Bar' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BarIntegrationTest.testFindBar() {
        Bar obj = dod.getRandomBar();
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bar' failed to provide an identifier", id);
        obj = barService.findBar(id);
        Assert.assertNotNull("Find method for 'Bar' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Bar' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BarIntegrationTest.testFindAllBars() {
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", dod.getRandomBar());
        long count = barService.countAllBars();
        Assert.assertTrue("Too expensive to perform a find all test for 'Bar', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Bar> result = barService.findAllBars();
        Assert.assertNotNull("Find all method for 'Bar' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Bar' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BarIntegrationTest.testFindBarEntries() {
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", dod.getRandomBar());
        long count = barService.countAllBars();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Bar> result = barService.findBarEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Bar' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Bar' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BarIntegrationTest.testSaveBar() {
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", dod.getRandomBar());
        Bar obj = dod.getNewTransientBar(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Bar' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Bar' identifier to be null", obj.getId());
        try {
            barService.saveBar(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'Bar' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BarIntegrationTest.testDeleteBar() {
        Bar obj = dod.getRandomBar();
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bar' failed to provide an identifier", id);
        obj = barService.findBar(id);
        barService.deleteBar(obj);
        Assert.assertNull("Failed to remove 'Bar' with identifier '" + id + "'", barService.findBar(id));
    }
    
}
