// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.verding.edo.model;

import it.verding.edo.model.Bar;
import it.verding.edo.model.Foo;
import it.verding.edo.model.FooDataOnDemand;
import it.verding.edo.service.FooService;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FooDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FooDataOnDemand: @Component;
    
    private Random FooDataOnDemand.rnd = new SecureRandom();
    
    private List<Foo> FooDataOnDemand.data;
    
    @Autowired
    FooService FooDataOnDemand.fooService;
    
    public Foo FooDataOnDemand.getNewTransientFoo(int index) {
        Foo obj = new Foo();
        setBar(obj, index);
        setBigdecimal(obj, index);
        setInteger(obj, index);
        setString(obj, index);
        return obj;
    }
    
    public void FooDataOnDemand.setBar(Foo obj, int index) {
        Bar bar = null;
        obj.setBar(bar);
    }
    
    public void FooDataOnDemand.setBigdecimal(Foo obj, int index) {
        BigDecimal bigdecimal = BigDecimal.valueOf(index);
        obj.setBigdecimal(bigdecimal);
    }
    
    public void FooDataOnDemand.setInteger(Foo obj, int index) {
        Integer integer = new Integer(index);
        obj.setInteger(integer);
    }
    
    public void FooDataOnDemand.setString(Foo obj, int index) {
        String string = "string_" + index;
        obj.setString(string);
    }
    
    public Foo FooDataOnDemand.getSpecificFoo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Foo obj = data.get(index);
        BigInteger id = obj.getId();
        return fooService.findFoo(id);
    }
    
    public Foo FooDataOnDemand.getRandomFoo() {
        init();
        Foo obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return fooService.findFoo(id);
    }
    
    public boolean FooDataOnDemand.modifyFoo(Foo obj) {
        return false;
    }
    
    public void FooDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = fooService.findFooEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Foo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Foo>();
        for (int i = 0; i < 10; i++) {
            Foo obj = getNewTransientFoo(i);
            try {
                fooService.saveFoo(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
