// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.verding.edo.model;

import it.verding.edo.model.FooDataOnDemand;
import it.verding.edo.model.FooIntegrationTest;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect FooIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FooIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FooIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    FooDataOnDemand FooIntegrationTest.dod;
    
    @Test
    public void FooIntegrationTest.testCountAllFoos() {
        Assert.assertNotNull("Data on demand for 'Foo' failed to initialize correctly", dod.getRandomFoo());
        long count = fooService.countAllFoos();
        Assert.assertTrue("Counter for 'Foo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FooIntegrationTest.testFindFoo() {
        Foo obj = dod.getRandomFoo();
        Assert.assertNotNull("Data on demand for 'Foo' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Foo' failed to provide an identifier", id);
        obj = fooService.findFoo(id);
        Assert.assertNotNull("Find method for 'Foo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Foo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FooIntegrationTest.testFindAllFoos() {
        Assert.assertNotNull("Data on demand for 'Foo' failed to initialize correctly", dod.getRandomFoo());
        long count = fooService.countAllFoos();
        Assert.assertTrue("Too expensive to perform a find all test for 'Foo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Foo> result = fooService.findAllFoos();
        Assert.assertNotNull("Find all method for 'Foo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Foo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FooIntegrationTest.testFindFooEntries() {
        Assert.assertNotNull("Data on demand for 'Foo' failed to initialize correctly", dod.getRandomFoo());
        long count = fooService.countAllFoos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Foo> result = fooService.findFooEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Foo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Foo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FooIntegrationTest.testSaveFoo() {
        Assert.assertNotNull("Data on demand for 'Foo' failed to initialize correctly", dod.getRandomFoo());
        Foo obj = dod.getNewTransientFoo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Foo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Foo' identifier to be null", obj.getId());
        try {
            fooService.saveFoo(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'Foo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FooIntegrationTest.testDeleteFoo() {
        Foo obj = dod.getRandomFoo();
        Assert.assertNotNull("Data on demand for 'Foo' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Foo' failed to provide an identifier", id);
        obj = fooService.findFoo(id);
        fooService.deleteFoo(obj);
        Assert.assertNull("Failed to remove 'Foo' with identifier '" + id + "'", fooService.findFoo(id));
    }
    
}
