// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.verding.edo.model;

import it.verding.edo.model.ZonaClimaticaDataOnDemand;
import it.verding.edo.model.ZonaClimaticaIntegrationTest;
import it.verding.edo.repositories.ZonaClimaticaRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.bson.types.ObjectId;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect ZonaClimaticaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ZonaClimaticaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ZonaClimaticaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    ZonaClimaticaDataOnDemand ZonaClimaticaIntegrationTest.dod;
    
    @Autowired
    ZonaClimaticaRepository ZonaClimaticaIntegrationTest.zonaClimaticaRepository;
    
    @Test
    public void ZonaClimaticaIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ZonaClimatica' failed to initialize correctly", dod.getRandomZonaClimatica());
        long count = zonaClimaticaRepository.count();
        Assert.assertTrue("Counter for 'ZonaClimatica' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ZonaClimaticaIntegrationTest.testFind() {
        ZonaClimatica obj = dod.getRandomZonaClimatica();
        Assert.assertNotNull("Data on demand for 'ZonaClimatica' failed to initialize correctly", obj);
        ObjectId id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZonaClimatica' failed to provide an identifier", id);
        obj = zonaClimaticaRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ZonaClimatica' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ZonaClimatica' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ZonaClimaticaIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ZonaClimatica' failed to initialize correctly", dod.getRandomZonaClimatica());
        long count = zonaClimaticaRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ZonaClimatica', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ZonaClimatica> result = zonaClimaticaRepository.findAll();
        Assert.assertNotNull("Find all method for 'ZonaClimatica' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ZonaClimatica' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ZonaClimaticaIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ZonaClimatica' failed to initialize correctly", dod.getRandomZonaClimatica());
        long count = zonaClimaticaRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ZonaClimatica> result = zonaClimaticaRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ZonaClimatica' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ZonaClimatica' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ZonaClimaticaIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ZonaClimatica' failed to initialize correctly", dod.getRandomZonaClimatica());
        ZonaClimatica obj = dod.getNewTransientZonaClimatica(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ZonaClimatica' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ZonaClimatica' identifier to be null", obj.getId());
        try {
            zonaClimaticaRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'ZonaClimatica' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ZonaClimaticaIntegrationTest.testDelete() {
        ZonaClimatica obj = dod.getRandomZonaClimatica();
        Assert.assertNotNull("Data on demand for 'ZonaClimatica' failed to initialize correctly", obj);
        ObjectId id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZonaClimatica' failed to provide an identifier", id);
        obj = zonaClimaticaRepository.findOne(id);
        zonaClimaticaRepository.delete(obj);
        Assert.assertNull("Failed to remove 'ZonaClimatica' with identifier '" + id + "'", zonaClimaticaRepository.findOne(id));
    }
    
}
