// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.verding.edo.model;

import it.verding.edo.model.ZonaClimatica;
import it.verding.edo.model.ZonaClimaticaDataOnDemand;
import it.verding.edo.repositories.ZonaClimaticaRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ZonaClimaticaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ZonaClimaticaDataOnDemand: @Component;
    
    private Random ZonaClimaticaDataOnDemand.rnd = new SecureRandom();
    
    private List<ZonaClimatica> ZonaClimaticaDataOnDemand.data;
    
    @Autowired
    ZonaClimaticaRepository ZonaClimaticaDataOnDemand.zonaClimaticaRepository;
    
    public ZonaClimatica ZonaClimaticaDataOnDemand.getNewTransientZonaClimatica(int index) {
        ZonaClimatica obj = new ZonaClimatica();
        setNome(obj, index);
        setValoreDaContoTermico(obj, index);
        return obj;
    }
    
    public void ZonaClimaticaDataOnDemand.setNome(ZonaClimatica obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void ZonaClimaticaDataOnDemand.setValoreDaContoTermico(ZonaClimatica obj, int index) {
        Integer valoreDaContoTermico = new Integer(index);
        obj.setValoreDaContoTermico(valoreDaContoTermico);
    }
    
    public ZonaClimatica ZonaClimaticaDataOnDemand.getSpecificZonaClimatica(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ZonaClimatica obj = data.get(index);
        ObjectId id = obj.getId();
        return zonaClimaticaRepository.findOne(id);
    }
    
    public ZonaClimatica ZonaClimaticaDataOnDemand.getRandomZonaClimatica() {
        init();
        ZonaClimatica obj = data.get(rnd.nextInt(data.size()));
        ObjectId id = obj.getId();
        return zonaClimaticaRepository.findOne(id);
    }
    
    public boolean ZonaClimaticaDataOnDemand.modifyZonaClimatica(ZonaClimatica obj) {
        return false;
    }
    
    public void ZonaClimaticaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = zonaClimaticaRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ZonaClimatica' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ZonaClimatica>();
        for (int i = 0; i < 10; i++) {
            ZonaClimatica obj = getNewTransientZonaClimatica(i);
            try {
                zonaClimaticaRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
