// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.verding.edo.model;

import it.verding.edo.model.ZonaClimaticaIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ZonaClimaticaIntegrationTest_Roo_Configurable {
    
    declare @type: ZonaClimaticaIntegrationTest: @Configurable;
    
}
